# Python Functions

## Example 1: Simple function with no arguments

In [1]:
def greet():
    print("Hello, world!")

In [2]:
greet()

Hello, world!


## Example 2: Function with arguments and a `return` statement

In [3]:
def add(a, b):
    return a + b

In [4]:
c = add(1, 2)
print(c)

3


## Example 3: Function with a default argument

In [5]:
def greet_user(name = "User"):
    print(f"Hello, {name}!")

In [6]:
greet_user("Abhishek")
greet_user()

Hello, Abhishek!
Hello, User!


## Example 4: Function returning multiple values

In [7]:
def divide(a, b):
    quotient = a // b
    remainder = a % b
    return quotient, remainder

In [8]:
q, r = divide(10, 3)
print("Quotient: ", q)
print("Remainder: ", r)

Quotient:  3
Remainder:  1


## Example 5: Recursive Function (Factorial)

In [9]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

In [10]:
print(f"Factorial of 5 is {factorial(5)}.")

Factorial of 5 is 120.


# `lambda` Functions

## Example 1: Simple `lambda` function to add two numbers

In [11]:
add = lambda x, y: x + y

In [12]:
print(add(1, 2))

3


## Example 2: `lambda` function with conditional satements

In [13]:
is_even = lambda x: True if x % 2 == 0 else False

In [14]:
print(is_even(2))

True


## Example 3: `lambda` function for string length

In [15]:
length_of_string = lambda s: len(s)

In [16]:
print(length_of_string("Hello, world!"))

13


## Example 4: `lambda` function to square a number

In [17]:
square = lambda x: x ** 2

In [18]:
print(f"Square of 2 is: {square(2)}")

Square of 2 is: 4


## Example 5: Using `lambda` inside a `map` function

In [19]:
numbers = [1, 2, 3, 4, 5]
squared_numbers = list(map(lambda x: x ** 2, numbers))

In [20]:
print(squared_numbers)

[1, 4, 9, 16, 25]


# Numpy

In [21]:
import numpy as np

## Example 1: Numpy array

In [22]:
arr = np.array([1, 2, 3, 4])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


## Example 2: Numpy array with zeros

In [23]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [24]:
matrix_of_ones = zeros + 1
print(matrix_of_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Example 3: Numpy array with random values

In [25]:
random_arr = np.random.rand(3, 3)
print(random_arr)

[[0.07091696 0.95823226 0.9849652 ]
 [0.3792453  0.02211018 0.49214727]
 [0.55217467 0.41725741 0.79141833]]


In [26]:
scaled_random_arr = random_arr * 10
print(scaled_random_arr)

[[0.70916964 9.58232259 9.84965198]
 [3.79245297 0.22110181 4.92147267]
 [5.52174669 4.17257412 7.91418332]]


## Example 4: Reshaping a Numpy array

In [27]:
reshaped_arr = np.reshape(arr, (2, 2))
print(reshaped_arr)

[[1 2]
 [3 4]]


In [28]:
column_vector = np.reshape(arr, (4, 1))
print(column_vector)

[[1]
 [2]
 [3]
 [4]]


## Example 5: Element-wise Operations

In [29]:
arr2 = np.array([5, 6, 7, 8])
sum_arr = arr + arr2
print(sum_arr)

[ 6  8 10 12]


In [30]:
product_arr = arr * arr2
print(product_arr)

[ 5 12 21 32]


# Pandas

In [31]:
import pandas as pd

## Example 1: Creating a DataFrame from a Dictionary

In [32]:
data = {"Name": ["Alice", "Bob", "Charlie"], "Age": [25, 30, 35]}
df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


## Example 2: Reading a CSV file

In [33]:
df2 = pd.read_csv("data.csv")
print(df2)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


## Example 3: Descriptive statistics of a DataFrame

In [34]:
df.describe()

Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [35]:
print(df.describe())

        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0


## Example 4: Selecting specific columns

In [36]:
names = df["Name"]
print(names)

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object


In [37]:
selected_columns = df[["Name", "Age"]]
print(selected_columns)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


## Example 5: Filtering data based on conditions

In [38]:
filtered_df = df[df["Age"] > 25]
print(filtered_df)

      Name  Age
1      Bob   30
2  Charlie   35


In [39]:
filtered_df2 = df[(df["Age"] > 25) & (df["Name"].str.startswith('C'))]
print(filtered_df2)

      Name  Age
2  Charlie   35


## Example 6: Reading a CSV with a custom delimiter

In [40]:
df3 = pd.read_csv("data.csv", delimiter = ',')
print(df3)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


## Exampel 7: Reading CSV and selecting columns

In [41]:
df4 = pd.read_csv("data.csv", usecols=["Name", "Age"])
print(df4)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


## Example 8: Reading a CSV and checking only the first few columns

In [42]:
print(df2.head()) # Prints only the first 5 rows.

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


## Example 9: Reading a CSV with specific data types

In [43]:
df5 = pd.read_csv("data.csv", dtype={"Age": "int"})
print(df5)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


# `if` statements

## Example 1: Simple `if` statement

In [44]:
# x = float(input("Enter any number: "))
x = 10
if x > 5:
    print("The number is greater than 5.")

The number is greater than 5.


## Example 2: `if`-`else` statement

In [45]:
# y = float(input("Enter any number: "))
y = 4
if y > 5:
    print("The number is greater than 5.")
else:
    print("The number is not greater than 5.")

The number is not greater than 5.


## Example 3: `if`-`elif`-`else` statement

In [46]:
# z = float(input("Enter any number: "))
z = 15
if z > 5:
    print("The number is greater than 5.")
elif z == 5:
    print("The number is 5.")
else:
    print("The number is less than 5.")

The number is greater than 5.


## Example 4: Nested `if` statements

In [47]:
# a = float(input("Enter any number: "))
a = 15
if a >= 10:
    if a <= 30:
        print("The number is between 10 and 30.")
else:
    print("The number is not between 10 and 30.")

The number is between 10 and 30.


## Example 5: Using `if` statements with logical operators

In [48]:
# b = float(input("Enter any number: "))
b = 15
if b >= 10 and b <= 30:
    print("The number is between 10 and 30.")
else:
    print("The number is not between 10 and 30.")

The number is between 10 and 30.


# Loops

## `for` Loop

### Example 1: Simple `for` loop

In [49]:
for i in range(5):
    print(i)

0
1
2
3
4


### Example 2: `for` loop over a list

In [50]:
numbers = [10, 20, 30, 40]
for number in numbers:
    print(number)

10
20
30
40


### Example 3: `for` loop with an index

In [51]:
fruits = ["Apple", "Banana", "Cherry"]
for i in range(len(fruits)):
    print(f"Index {i}: {fruits[i]}")

Index 0: Apple
Index 1: Banana
Index 2: Cherry


### Example 4: Nested `for` loop

In [52]:
for i in range(1, 4):
    for j in range(1, 4):
        print(f"i = {i}, j = {j}")

i = 1, j = 1
i = 1, j = 2
i = 1, j = 3
i = 2, j = 1
i = 2, j = 2
i = 2, j = 3
i = 3, j = 1
i = 3, j = 2
i = 3, j = 3


### Example 5: `for` loop with `else`

In [53]:
for i in range(3):
    print(i)
else:
    print("Loop finished!")

0
1
2
Loop finished!


### Example 6: `for` loop with `break`

In [54]:
for i in range(10):
    if i == 5:
        break
    print(i)

0
1
2
3
4


## `while` Loop

### Example 1: Simple `while` loop

In [55]:
count = 0
while count < 5:
    print(count)
    count += 1

0
1
2
3
4


### Example 2: `while` loop with user `input`

In [56]:
password = "secret"
enter_password = ""
while enter_password != password:
    enter_password = input("Enter password: ")
print("Access granted!")

Enter password:  secret


Access granted!


### Example 3: `while` loop with `break`

In [57]:
x = 0
while x < 10:
    if x == 5:
        break
    print(x)
    x += 1

0
1
2
3
4


### Example 4: `while` loop with `continue`

In [58]:
x = 0
while x < 10:
    x += 1
    if x % 2 == 0:
        continue
    print(x)

1
3
5
7
9


### Example 5: Infinite `while` loop with `break`

In [59]:
i = 0
while True:
    print(i)
    i += 1
    if i >= 3:
        break

0
1
2


# Lists, Tuples, Sets and Dictionaries

## Lists

### Example 1: Creating a list

In [60]:
fruits = ["Apple", "Banana", "Cherry"]
print(fruits)

['Apple', 'Banana', 'Cherry']


### Example 2: Appending to a list

In [61]:
fruits.append("Orange")
print(fruits)

['Apple', 'Banana', 'Cherry', 'Orange']


### Example 3: Accessing list elements by index

In [62]:
print(fruits[0])
print(fruits[-1])

Apple
Orange


### Example 4: Removing elements from a list

In [63]:
fruits.remove("Banana")
print(fruits)

['Apple', 'Cherry', 'Orange']


### Example 5: Slicing a list

In [64]:
print(fruits[1:3])
print(fruits)

['Cherry', 'Orange']
['Apple', 'Cherry', 'Orange']


## Tuples

### Example 1: Creating a tuple

In [65]:
coordinates = (10, 20)
print(coordinates)

(10, 20)


### Example 2: Accessing tuple elements by index

In [66]:
print(coordinates[0])

10


### Example 3: Nested tupels

In [67]:
nested_tuple = ((1, 2), (3, 4))
print(nested_tuple)

((1, 2), (3, 4))


### Example 4: Immutable nature of tuples

In [68]:
# coordinates[0] = 15
# This would raise a "TypeError" because tuples are immutable.

### Example 5: Tuple unpacking

In [69]:
x, y = coordinates
print(x, y)

10 20


## Sets

### Example 1: Creating a set

In [70]:
unique_numbers = {1, 2, 3, 3, 4}
print(unique_numbers)

{1, 2, 3, 4}


### Example 2: Adding an element to a set

In [71]:
unique_numbers.add(5)
print(unique_numbers)

{1, 2, 3, 4, 5}


### Example 3: Set union

In [72]:
set_a = {1, 2, 3}
set_b = {3, 4, 5}
union_set = set_a.union(set_b)
print(union_set)

{1, 2, 3, 4, 5}


### Example 4: Set intersection

In [73]:
intersection_set = set_a.intersection(set_b)
print(intersection_set)

{3}


### Example 5: Removing an element from a set

In [74]:
unique_numbers.remove(2)
print(unique_numbers)

{1, 3, 4, 5}


## Dictionaries

### Example 1: Creating a dictionary

In [75]:
person = {"name": "Alice", "age": 25}
print(person)

{'name': 'Alice', 'age': 25}


### Example 2: Accessing dictionary values by keys

In [76]:
print(person["name"])

Alice


### Example 3: Adding a new key-value pair to the dictionary

In [77]:
person["city"] = "New York"
print(person)

{'name': 'Alice', 'age': 25, 'city': 'New York'}


### Example 4: Updating a dictionary value

In [78]:
person["age"] = 30
print(person)

{'name': 'Alice', 'age': 30, 'city': 'New York'}


### Example 5: Looping over a dictionary

In [79]:
for key, value in person.items():
    print(f"{key}: {value}")

name: Alice
age: 30
city: New York


# Operators

## Arithmetic Operators

### Example 1: Addition and Subtraction

In [80]:
x = 10
y = 5
add = x + y
subtract = x - y
print(add)
print(subtract)

15
5


### Example 2: Multiplication and Division

In [81]:
product = x * y
division = x / y
print(product)
print(division)

50
2.0


### Example 3: Modulus

In [82]:
remainder = x % y
print(remainder)

0


### Example 4: Quotient (Floor Division)

In [83]:
quotient = x // y
print(quotient)

2


### Example 5: Exponentiation

In [84]:
power = x ** 2
print(power)

100


## Comparison Operators

### Example 1: Equals

In [85]:
is_equal = (x == y)
print(is_equal)

False


### Example 2: Does not equal

In [86]:
is_not_equal = (x != y)
print(is_not_equal)

True


### Example 3: Greater than

In [87]:
is_greater = (x > y)
print(is_greater)

True


### Example 4: Less than or equal to

In [88]:
is_less_or_equal = (x <= y)
print(is_less_or_equal)

False


### Example 5: Greater than or equal to

In [89]:
is_greater_or_equal = (x >= y)
print(is_greater_or_equal)

True


## Logical Operators

### Example 1: `and` operator

In [90]:
and_result = (x > 5 and y < 10)
print(and_result)

True


### Example 2: `or` operator

In [91]:
or_result = (x > 15 or y == 5)
print(or_result)

True


### Example 3: `not` operator

In [92]:
not_result = not(x == y)
print(not_result)

True


### Example 4: Combining `and` and `or` operators

In [93]:
combined_logic = (x > 5 and y ==5) or (y > 10)
print(combined_logic)

True


### Example 5: Nested logical operations

In [94]:
nested_result = ((x > 5 or y > 5) and (x < 20))
print(nested_result)

True


## Assignment Operators

### Example 1: Assignment

In [95]:
x = 10
print(x)

10


### Example 2: Addition Assignment

In [96]:
x += 5
print(x)

15


### Example 3: Subtraction Assignment

In [97]:
x -= 3
print(x)

12


### Example 4: Multiplication Assignment

In [98]:
x *= 2
print(x)

24


### Example 5: Division Assignment

In [99]:
x /= 2
print(x)

12.0


### Example 6: Modulus Assignment

In [100]:
x %= 3
print(x)

0.0


## Identity Operators

### Example 1: `is` operator

In [101]:
a = 10
b = 10
is_same = (a is b) # They point to the same object in the memory.
print(is_same)

True


### Exampel 2: `is not` operator

In [102]:
a = [1, 2, 3]
b = [1, 2, 3]
is_not_same = (a is not b) # They point to different objects in the memory.
print(is_not_same)

True


### Example 3: Using `is` with `None`

In [103]:
result = None
is_none = (result is None)
print(is_none)

True


### Example 4: Comparing mutable objects with `is`

In [104]:
list1 = [1, 2, 3]
list2 = list1
is_same_list = (list1 is list2) # They point to the same object in the memory.
print(is_same_list)

True


### Example 5: Comparing large integers with `is`

In [105]:
x = 1000
y = 1000
print(x is y) # Large integers are allocated with separate memories.

False


# Reading CSV Files

In [106]:
import csv

## Example 1: Basic CSV file reading

In [107]:
with open("data.csv", 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['Name', 'Age']
['Alice', '25']
['Bob', '30']
['Charlie', '35']


## Example 2: Reading CSV and splitting by a custom delimiter

In [108]:
with open("data.csv", 'r') as file:
    reader = csv.reader(file, delimiter = ',')
    for row in reader:
        print(row)

['Name', 'Age']
['Alice', '25']
['Bob', '30']
['Charlie', '35']


## Example 3: Reading specific columns by index

In [109]:
with open("data.csv", 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(f"Name: {row[0]}, Age: {row[1]}")

Name: Name, Age: Age
Name: Alice, Age: 25
Name: Bob, Age: 30
Name: Charlie, Age: 35


## Example 4: Skipping the header row

In [110]:
with open("data.csv", 'r') as file:
    reader = csv.reader(file)
    next(reader)
    for row in reader:
        print(row)

['Alice', '25']
['Bob', '30']
['Charlie', '35']


## Example 5: Reading CSV into a dictionary

In [111]:
with open("data.csv", 'r') as file:
    reader = csv.DictReader(file)
    for row in reader:
        print(dict(row))

{'Name': 'Alice', 'Age': '25'}
{'Name': 'Bob', 'Age': '30'}
{'Name': 'Charlie', 'Age': '35'}


# Python String Methods

## Example 1: Uppercase conversion

In [112]:
text = "Hello, world!"
print(text.upper())

HELLO, WORLD!


## Example 2: String splitting

In [113]:
words = text.split()
print(words)

['Hello,', 'world!']


## Example 3: String replacement

In [114]:
new_text = text.replace("world", "Python")
print(new_text)

Hello, Python!


## Example 4: String stripping (removing whitespaces)

In [115]:
trimmed_text = "     Hello, world!   ".strip()
print(trimmed_text)

Hello, world!


## Example 5: String concatenation

In [116]:
greeting = "Hello, " + "world!"
print(greeting)

Hello, world!
