# Python Functions

## Example 1: Simple function with no arguments

In [1]:
def greet():
    print("Hello, world!")

In [2]:
greet()

Hello, world!


## Example 2: Function with arguments and a `return` statement (and a use of a docstring)

In [3]:
def add(a, b):
    """
    Takes two number variable inputs using two arguments: a, b.
    Returns the sum of the two numbers.
    """
    return a + b

In [4]:
c = add(1, 2)
print(c)

3


## Example 3: Function with a default argument

In [5]:
def greet_user(name = "User"):
    print(f"Hello, {name}!")

In [6]:
greet_user("Abhishek")
greet_user()

Hello, Abhishek!
Hello, User!


## Example 4: Function returning multiple values

In [7]:
def divide(a, b):
    quotient = a // b
    remainder = a % b
    return quotient, remainder

In [8]:
q, r = divide(10, 3)
print("Quotient: ", q)
print("Remainder: ", r)

Quotient:  3
Remainder:  1


## Example 5: Recursive Function (Factorial)

In [9]:
def factorial(n):
    if n == 0 or n == 1:
        return 1
    else:
        return n * factorial(n - 1)

In [10]:
print(f"Factorial of 5 is {factorial(5)}.")

Factorial of 5 is 120.


## Example 6: Function scope and variable accessibility

In [11]:
x = 10
def outer_function():
    y = 20
    print(f"Inside outer_funciton, x (global): {x}")
    def inner_function():
        z = 30
        print(f"Inside inner_function, x (global): {x}")
        print(f"Inside inner_function, y (enclosing scope): {y}")
        print(f"Inside inner_function, z (local): {z}")
    inner_function()

In [12]:
outer_function()

Inside outer_funciton, x (global): 10
Inside inner_function, x (global): 10
Inside inner_function, y (enclosing scope): 20
Inside inner_function, z (local): 30


# `lambda` Functions

## Example 1: Simple `lambda` function to add two numbers

In [13]:
add = lambda x, y: x + y

In [14]:
print(add(1, 2))

3


## Example 2: Comparing the above `lambda` function to a regular function

In [15]:
def regular_add(a, b):
    return a + b

In [16]:
print (regular_add(1, 2))

3


## Example 3: `lambda` function with conditional satements

In [17]:
is_even = lambda x: True if x % 2 == 0 else False

In [18]:
print(is_even(2))

True


## Example 4: `lambda` function for string length

In [19]:
length_of_string = lambda s: len(s)

In [20]:
print(length_of_string("Hello, world!"))

13


## Example 5: `lambda` function to square a number

In [21]:
square = lambda x: x ** 2

In [22]:
print(f"Square of 2 is: {square(2)}")

Square of 2 is: 4


## Example 6: Using `lambda` inside a `map()` function

In [23]:
numbers = [1, 2, 3, 4, 5]
squared_numbers = list(map(lambda x: x ** 2, numbers))

In [24]:
print(squared_numbers)

[1, 4, 9, 16, 25]


## Example 7: Using `lambda` inside a `filter()` function

In [25]:
even_numbers = list(filter(lambda x: x % 2 == 0, numbers))

In [26]:
print(even_numbers)

[2, 4]


## Example 8: Using `lambda` inside a `reduce()` funciton

In [27]:
from functools import reduce
product = reduce(lambda x, y: x * y, numbers)

In [28]:
print(product)

120


# Numpy

In [29]:
import numpy as np

## Example 1: Numpy array

In [30]:
arr = np.array([1, 2, 3, 4])
print(arr)
print(type(arr))
print(arr.shape)

[1 2 3 4]
<class 'numpy.ndarray'>
(4,)


## Example 2: Numpy 2D array

In [31]:
arr_2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
print(arr_2d)

[[1 2 3 4]
 [5 6 7 8]]


## Example 3: Numpy 3D array

In [32]:
arr_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print(arr_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Example 4: Numpy array with zeros

In [33]:
zeros = np.zeros((3, 3))
print(zeros)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [34]:
matrix_of_ones = zeros + 1
print(matrix_of_ones)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


## Example 5: Numpy array with random values

In [35]:
random_arr = np.random.rand(3, 3)
print(random_arr)

[[0.86414023 0.34150218 0.79939835]
 [0.67788923 0.6155338  0.51734658]
 [0.17102768 0.03436858 0.93412088]]


In [36]:
scaled_random_arr = random_arr * 10
print(scaled_random_arr)

[[8.64140227 3.41502177 7.99398352]
 [6.77889229 6.155338   5.17346577]
 [1.71027678 0.34368578 9.34120881]]


In [37]:
random_integers = np.random.randint(0, 10, size=(3, 3))
print(random_integers)

[[3 2 5]
 [1 2 5]
 [5 9 4]]


In [38]:
random_normal = np.random.randn(3, 3) # Random numbers for normal distribution
print(random_normal)

[[-0.78749556  0.84225378  0.55873971]
 [ 0.53414162  0.74321116  0.9189213 ]
 [ 0.35409317  1.36541717 -0.61056056]]


In [39]:
np.random.seed(42)  # Setting a seed ensures reproducibility
random_seeded = np.random.rand(3, 3)
print(random_seeded)

[[0.37454012 0.95071431 0.73199394]
 [0.59865848 0.15601864 0.15599452]
 [0.05808361 0.86617615 0.60111501]]


In [40]:
arr_to_shuffle = np.array([1, 2, 3, 4, 5])
np.random.shuffle(arr_to_shuffle) # Suffling arrays
print(arr_to_shuffle)

[5 4 1 2 3]


## Example 6: Reshaping a Numpy array

In [41]:
reshaped_arr = np.reshape(arr, (2, 2))
print(reshaped_arr)

[[1 2]
 [3 4]]


In [42]:
column_vector = np.reshape(arr, (4, 1))
print(column_vector)

[[1]
 [2]
 [3]
 [4]]


## Example 7: Element-wise Operations

In [43]:
arr2 = np.array([5, 6, 7, 8])
sum_arr = arr + arr2
print(sum_arr)

[ 6  8 10 12]


In [44]:
product_arr = arr * arr2
print(product_arr)

[ 5 12 21 32]


## Eample 8: Scalar Addition

In [45]:
scalar_addition = arr + 10
print(scalar_addition)

[11 12 13 14]


## Example 9: Accessing elements in a Numpy array using indices

In [46]:
print(arr[2])
print(arr_2d[1, 2])
print(arr_3d[1, 0, 1])

3
7
6


## Example 10: Slicing Numpy arrays

In [47]:
print(arr[1:4])
print(arr_2d[:2, :2])

[2 3 4]
[[1 2]
 [5 6]]


## Example 11: Transposing a Numpy array (flipping rows and columns)

In [48]:
transposed = arr_2d.T
print(transposed)

[[1 5]
 [2 6]
 [3 7]
 [4 8]]


## Example 12: Concatenating Numpy arrays

In [49]:
concatenated = np.concatenate((arr, arr2))
print(concatenated)

[1 2 3 4 5 6 7 8]


In [50]:
concatenated_2d = np.concatenate((arr_2d, arr_2d), axis = 0)
print(concatenated_2d)

[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


# Pandas

In [51]:
import pandas as pd

## Example 1: Creating a DataFrame from a Dictionary

In [52]:
data = {"Name": ["Alice", "Bob", "Charlie"], "Age": [25, 30, 35, ]}
df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


## Example 2: Reading a CSV file

In [53]:
df2 = pd.read_csv("data.csv")
print(df2)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


## Example 3: Descriptive statistics of a DataFrame

In [54]:
df.describe()

Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0

In [55]:
print(df.describe())

        Age
count   3.0
mean   30.0
std     5.0
min    25.0
25%    27.5
50%    30.0
75%    32.5
max    35.0


## Example 4: Selecting specific columns

In [56]:
names = df["Name"]
print(names)

0      Alice
1        Bob
2    Charlie
Name: Name, dtype: object


In [57]:
selected_columns = df[["Name", "Age"]]
print(selected_columns)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


## Example 5: Filtering data based on conditions

In [58]:
filtered_df = df[df["Age"] > 25]
print(filtered_df)

      Name  Age
1      Bob   30
2  Charlie   35


In [59]:
filtered_df2 = df[(df["Age"] > 25) & (df["Name"].str.startswith('C'))]
print(filtered_df2)

      Name  Age
2  Charlie   35


## Example 6: Reading a CSV with a custom delimiter

In [60]:
df3 = pd.read_csv("data.csv", delimiter = ',')
print(df3)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


## Exampel 7: Reading CSV and selecting columns

In [61]:
df4 = pd.read_csv("data.csv", usecols=["Name", "Age"])
print(df4)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


## Example 8: Reading a CSV and checking only the first few columns

In [62]:
print(df2.head()) # Prints only the first 5 rows.

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


## Example 9: Reading a CSV with specific data types

In [63]:
df5 = pd.read_csv("data.csv", dtype={"Age": "int"})
print(df5)

      Name  Age
0    Alice   25
1      Bob   30
2  Charlie   35


## Example 10: Grouping data

In [64]:
grouped_df = df.groupby("Age").count()
print(grouped_df)

     Name
Age      
25      1
30      1
35      1


## Example 11: Pivot tables

In [65]:
pivot_table = df.pivot_table(values="Age", index="Name")
print(pivot_table)

          Age
Name         
Alice    25.0
Bob      30.0
Charlie  35.0


## Example 12: Skipping rows

In [66]:
df6 = pd.read_csv("data.csv", skiprows=2) # Skipping first two rows
print(df6)

       Bob  30
0  Charlie  35


## Example 13: Specifying rows to use as column names

In [67]:
df7 = pd.read_csv("data.csv", header=2) # Using the third row, index 2, as the header row
print(df7)

       Bob  30
0  Charlie  35


## Example 14: Filling missing values with a default value

In [68]:
df8 = pd.read_csv("data2.csv")
df_filled = df8.fillna(0)
print(df_filled)

       Name   Age
0     Alice  25.0
1       Bob  30.0
2   Charlie  35.0
3  Abhishek   0.0
4       Bob  30.0


## Example 15: Dropping rows with missing data

In [69]:
df_cleaned = df8.dropna()
print(df_cleaned)

      Name   Age
0    Alice  25.0
1      Bob  30.0
2  Charlie  35.0
4      Bob  30.0


## Example 16: Removing Duplicates

In [70]:
df_no_duplicates = df8.drop_duplicates()
print(df_no_duplicates)

       Name   Age
0     Alice  25.0
1       Bob  30.0
2   Charlie  35.0
3  Abhishek   NaN


## Example 17: Renaming columns

In [71]:
df_renamed = df2.rename(columns={"Name": "Full Name", "Age": "Years"})
print(df_renamed)

  Full Name  Years
0     Alice     25
1       Bob     30
2   Charlie     35


# `if` statements

## Example 1: Simple `if` statement

In [72]:
# x = float(input("Enter any number: "))
x = 10
if x > 5:
    print("The number is greater than 5.")

The number is greater than 5.


## Example 2: `if`-`else` statement

In [73]:
# y = float(input("Enter any number: "))
y = 4
if y > 5:
    print("The number is greater than 5.")
else:
    print("The number is not greater than 5.")

The number is not greater than 5.


## Example 3: `if`-`elif`-`else` statement

In [74]:
# z = float(input("Enter any number: "))
z = 15
if z > 5:
    print("The number is greater than 5.")
elif z == 5:
    print("The number is 5.")
else:
    print("The number is less than 5.")

The number is greater than 5.


## Example 4: Nested `if` statements

In [75]:
# a = float(input("Enter any number: "))
a = 15
if a >= 10:
    if a <= 30:
        print("The number is between 10 and 30.")
else:
    print("The number is not between 10 and 30.")

The number is between 10 and 30.


## Example 5: Using `if` statements with logical operators

In [76]:
# b = float(input("Enter any number: "))
b = 15
if b >= 10 and b <= 30:
    print("The number is between 10 and 30.")
elif b > 30:
    print("The number is greater than 30.")
else:
    print("The number is less than 10.")

The number is between 10 and 30.


# Loops

## `for` Loop

### Example 1: Simple `for` loop

In [77]:
for i in range(5):
    print(i)

0
1
2
3
4


### Example 2: `for` loop over a list

In [78]:
numbers = [10, 20, 30, 40]
for number in numbers:
    print(number)

10
20
30
40


### Example 3: `for` loop with an index

In [79]:
fruits = ["Apple", "Banana", "Cherry"]
for i in range(len(fruits)):
    print(f"Index {i}: {fruits[i]}")

Index 0: Apple
Index 1: Banana
Index 2: Cherry


### Example 4: Nested `for` loop

In [80]:
for i in range(1, 4):
    for j in range(1, 4):
        print(f"i = {i}, j = {j}")

i = 1, j = 1
i = 1, j = 2
i = 1, j = 3
i = 2, j = 1
i = 2, j = 2
i = 2, j = 3
i = 3, j = 1
i = 3, j = 2
i = 3, j = 3


### Example 5: `for` loop with `else`

In [81]:
for i in range(3):
    print(i)
else:
    print("Loop finished!")

0
1
2
Loop finished!


### Example 6: `for` loop with `break`

In [82]:
for i in range(10):
    if i == 5:
        break
    print(i)

0
1
2
3
4


## `while` Loop

### Example 1: Simple `while` loop

In [83]:
count = 0
while count < 5:
    print(count)
    count += 1

0
1
2
3
4


### Example 2: `while` loop with user `input`

In [84]:
password = "secret"
enter_password = ""
while enter_password != password:
    enter_password = input("Enter password: ")
print("Access granted!")

Enter password:  secret


Access granted!


### Example 3: `while` loop with `break`

In [85]:
x = 0
while x < 10:
    if x == 5:
        break
    print(x)
    x += 1

0
1
2
3
4


### Example 4: `while` loop with `continue`

In [86]:
x = 0
while x < 10:
    x += 1
    if x % 2 == 0:
        continue
    print(x)

1
3
5
7
9


### Example 5: Infinite `while` loop with `break`

In [87]:
i = 0
while True:
    print(i)
    i += 1
    if i >= 3:
        break

0
1
2


# Lists, Tuples, Sets and Dictionaries

## Lists

### Example 1: Creating a list

In [88]:
fruits = ["Apple", "Banana", "Cherry"]
print(fruits)

['Apple', 'Banana', 'Cherry']


### Example 2: Appending to a list

In [89]:
fruits.append("Orange")
print(fruits)

['Apple', 'Banana', 'Cherry', 'Orange']


### Example 3: Accessing list elements by index

In [90]:
print(fruits[0])
print(fruits[-1])

Apple
Orange


### Example 4: Removing elements from a list

In [91]:
fruits.remove("Banana")
print(fruits)

['Apple', 'Cherry', 'Orange']


### Example 5: Slicing a list

In [92]:
print(fruits[1:3])
print(fruits)

['Cherry', 'Orange']
['Apple', 'Cherry', 'Orange']


## Tuples

### Example 1: Creating a tuple

In [93]:
coordinates = (10, 20)
print(coordinates)

(10, 20)


### Example 2: Accessing tuple elements by index

In [94]:
print(coordinates[0])

10


### Example 3: Nested tupels

In [95]:
nested_tuple = ((1, 2), (3, 4))
print(nested_tuple)

((1, 2), (3, 4))


### Example 4: Immutable nature of tuples

In [96]:
# coordinates[0] = 15
# This would raise a "TypeError" because tuples are immutable.

### Example 5: Tuple unpacking

In [97]:
x, y = coordinates
print(x, y)

10 20


## Sets

### Example 1: Creating a set

In [98]:
unique_numbers = {1, 2, 3, 3, 4}
print(unique_numbers)

{1, 2, 3, 4}


### Example 2: Adding an element to a set

In [99]:
unique_numbers.add(5)
print(unique_numbers)

{1, 2, 3, 4, 5}


### Example 3: Set union

In [100]:
set_a = {1, 2, 3}
set_b = {3, 4, 5}
union_set = set_a.union(set_b)
print(union_set)

{1, 2, 3, 4, 5}


### Example 4: Set intersection

In [101]:
intersection_set = set_a.intersection(set_b)
print(intersection_set)

{3}


### Example 5: Removing an element from a set

In [102]:
unique_numbers.remove(2)
print(unique_numbers)

{1, 3, 4, 5}


## Dictionaries

### Example 1: Creating a dictionary

In [103]:
person = {"name": "Alice", "age": 25}
print(person)

{'name': 'Alice', 'age': 25}


### Example 2: Accessing dictionary values by keys

In [104]:
print(person["name"])

Alice


### Example 3: Adding a new key-value pair to the dictionary

In [105]:
person["city"] = "New York"
print(person)

{'name': 'Alice', 'age': 25, 'city': 'New York'}


### Example 4: Updating a dictionary value

In [106]:
person["age"] = 30
print(person)

{'name': 'Alice', 'age': 30, 'city': 'New York'}


### Example 5: Looping over a dictionary

In [107]:
for key, value in person.items():
    print(f"{key}: {value}")

name: Alice
age: 30
city: New York


# Operators

## Arithmetic Operators

### Example 1: Addition and Subtraction

In [108]:
x = 10
y = 5
add = x + y
subtract = x - y
print(add)
print(subtract)

15
5


### Example 2: Multiplication and Division

In [109]:
product = x * y
division = x / y
print(product)
print(division)

50
2.0


### Example 3: Modulus

In [110]:
remainder = x % y
print(remainder)

0


### Example 4: Quotient (Floor Division)

In [111]:
quotient = x // y
print(quotient)

2


### Example 5: Exponentiation

In [112]:
power = x ** 2
print(power)

100


### Example 6: Operator precedance

In [113]:
result = 10 + 2 * 3 ** 2 / 6 - 4
print("Result: ", result)

Result:  9.0


In [114]:
result2 = (10 +2) * (3 ** (2/6) - 4)
print("Result2: ", result2)

Result2:  -30.693005156311102


## Comparison Operators

### Example 1: Equals

In [115]:
is_equal = (x == y)
print(is_equal)

False


### Example 2: Does not equal

In [116]:
is_not_equal = (x != y)
print(is_not_equal)

True


### Example 3: Greater than

In [117]:
is_greater = (x > y)
print(is_greater)

True


### Example 4: Less than or equal to

In [118]:
is_less_or_equal = (x <= y)
print(is_less_or_equal)

False


### Example 5: Greater than or equal to

In [119]:
is_greater_or_equal = (x >= y)
print(is_greater_or_equal)

True


## Logical Operators

### Example 1: `and` operator

In [120]:
and_result = (x > 5 and y < 10)
print(and_result)

True


### Example 2: `or` operator

In [121]:
or_result = (x > 15 or y == 5)
print(or_result)

True


### Example 3: `not` operator

In [122]:
not_result = not(x == y)
print(not_result)

True


### Example 4: Combining `and` and `or` operators

In [123]:
combined_logic = (x > 5 and y ==5) or (y > 10)
print(combined_logic)

True


### Example 5: Nested logical operations

In [124]:
nested_result = ((x > 5 or y > 5) and (x < 20))
print(nested_result)

True


## Assignment Operators

### Example 1: Assignment

In [125]:
x = 10
print(x)

10


### Example 2: Addition Assignment

In [126]:
x += 5
print(x)

15


### Example 3: Subtraction Assignment

In [127]:
x -= 3
print(x)

12


### Example 4: Multiplication Assignment

In [128]:
x *= 2
print(x)

24


### Example 5: Division Assignment

In [129]:
x /= 2
print(x)

12.0


### Example 6: Modulus Assignment

In [130]:
x %= 3
print(x)

0.0


## Identity Operators

### Example 1: `is` operator

In [131]:
a = 10
b = 10
is_same = (a is b) # They point to the same object in the memory.
print(is_same)

True


### Exampel 2: `is not` operator

In [132]:
a = [1, 2, 3]
b = [1, 2, 3]
is_not_same = (a is not b) # They point to different objects in the memory.
print(is_not_same)

True


### Example 3: Using `is` with `None`

In [133]:
result = None
is_none = (result is None)
print(is_none)

True


### Example 4: Comparing mutable objects with `is`

In [134]:
list1 = [1, 2, 3]
list2 = list1
is_same_list = (list1 is list2) # They point to the same object in the memory.
print(is_same_list)

True


### Example 5: Comparing large integers with `is`

In [135]:
x = 1000
y = 1000
print(x is y) # Large integers are allocated with separate memories.

False


# Reading CSV Files

In [136]:
import csv

## Example 1: Basic CSV file reading

In [137]:
with open("data.csv", 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(row)

['Name', 'Age']
['Alice', '25']
['Bob', '30']
['Charlie', '35']


## Example 2: Reading CSV and splitting by a custom delimiter

In [138]:
with open("data.csv", 'r') as file:
    reader = csv.reader(file, delimiter = ',')
    for row in reader:
        print(row)

['Name', 'Age']
['Alice', '25']
['Bob', '30']
['Charlie', '35']


## Example 3: Reading specific columns by index

In [139]:
with open("data.csv", 'r') as file:
    reader = csv.reader(file)
    for row in reader:
        print(f"Name: {row[0]}, Age: {row[1]}")

Name: Name, Age: Age
Name: Alice, Age: 25
Name: Bob, Age: 30
Name: Charlie, Age: 35


## Example 4: Skipping the header row

In [140]:
with open("data.csv", 'r') as file:
    reader = csv.reader(file)
    next(reader)
    for row in reader:
        print(row)

['Alice', '25']
['Bob', '30']
['Charlie', '35']


## Example 5: Reading CSV into a dictionary

In [141]:
with open("data.csv", 'r') as file:
    reader = csv.DictReader(file)
    for row in reader:
        print(dict(row))

{'Name': 'Alice', 'Age': '25'}
{'Name': 'Bob', 'Age': '30'}
{'Name': 'Charlie', 'Age': '35'}


# Python String Methods

## Example 1: Case conversion

In [142]:
text = "Hello, world!"
print(text.upper())

HELLO, WORLD!


In [143]:
print(text.lower())

hello, world!


In [144]:
print(text.title())

Hello, World!


## Example 2: String splitting

In [145]:
words = text.split()
print(words)

['Hello,', 'world!']


In [146]:
print(text.split(",")) # Splitting text using a custom delimiter

['Hello', ' world!']


## Example 3: String replacement

In [147]:
new_text = text.replace("world", "Python")
print(new_text)

Hello, Python!


## Example 4: String stripping (removing leading and trailing whitespaces)

In [148]:
text2 = "     Hello, world!   "
print(text2.strip())

Hello, world!


In [149]:
print(text2.lstrip())

Hello, world!   


In [150]:
print(text2.rstrip())

     Hello, world!


## Example 5: String concatenation

In [151]:
greeting = "Hello, " + "world!"
print(greeting)

Hello, world!


## Example 6: Finding the first occurrence of a substring

In [152]:
index = text.find("world!")
print(index)

7


## Example 7: Counting the number of occurences of a substring in a string

In [153]:
count = text.count('o')
print(count)

2


## Example 8: Checking if a stirng starts or ends with a certain substring

In [154]:
print(text.startswith("Hello"))
print(text.endswith("world!"))

True
True


## Example 9: String slicing

In [155]:
sliced_text = text[3:5]
print(sliced_text)

lo
